jobs:
  include:
    - language: cpp
      before_install:
        - pip install --user cpp-coveralls
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - doxygen
            - g++-6
            - ninja-build
      script:
        - mkdir build && cd build
        - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6
          cmake -DCMAKE_BUILD_TYPE=Coverage -G Ninja ..
        - cmake --build .
        - cmake --build . --target test
        - cmake --build . --target dox
      after_success:
        - coveralls -r $TRAVIS_BUILD_DIR -b $TRAVIS_BUILD_DIR/build
                    --gcov '/usr/bin/gcov-6' --gcov-options '\-lp'
                    -i lib -e target
    - language: cpp
      addons:
        apt:
          packages:
            - avr-libc
            - cmake
            - ninja-build
      script:
        - mkdir build && cd build
        - cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/avr/generic-gcc-avr.cmake
                -DBUILD_DOCUMENTATION=OFF
                -DTARGET_CONFIGURATION=arduino
                -DAVR_MCU=atmega328p
                -G Ninja ..
        - cmake --build .
    - language: python
      python: 3.6
      install: pip install tox
      script: cd tools && tox -e py36
